server:
  port: 7909
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
spring:
  application:
    name: microservice-consumer-movie-feign
logging:
  level:
    com.chenjj.UserFeignClient: DEBUG