server:
  port: 7913
# 注册到eureka的http://user:password123@localhost:8761/eureka/上
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka/
  instance:
    #使用ip地址
    prefer-ip-address: true
    #在eureka控制台上显示的名称
    instance-id: ${spring.application.name}:${server.port}
spring:
  application:
    name: microservice-consumer-movie-feign-with-hystrix-hystrixfactory