server:
  port: 8031
spring:
  application:
    name: microservice-hystrix-turbine2
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
turbine:
  aggregator:
    clusterConfig: MICROSERVICE-CONSUMER-MOVIE-RIBBON-WITH-HYSTRIX2
  appConfig: microservice-consumer-movie-ribbon-with-hystrix2
  instanceUrlSuffix:
    MICROSERVICE-CONSUMER-MOVIE-RIBBON-WITH-HYSTRIX2: /ribbonwithhystrix2/hystrix.stream
logging:
  level:
    root: INFO
    com.netflix.turbine.monitor: DEBUG