server:
  port: 7907
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
spring:
  application:
    name: microservice-consumer-movie-ribbon
ribbon:
  eureka:
    enabled: false
    #不用eureka
microservice-provider-user:
  ribbon:
    listOfServers: localhost:7900